### ISSUE TITLE
Ubuntu 14.04 with mono failing to execute simple query

### ISSUE THREAD

**Issue by exilonX** [tjanczuk/edge-sql#12]
I am executing a simple query on a remote SQL Server Database using this code: 

var edge        = require('edge');

var CONST_CONNECTION = "Data Source=10.6.65.233;Initial Catalog=MyDB;User Id=remote; Password=remote;";

var selectAll = edge.func('sql', {
    connectionString: CONST_CONNECTION,
    source: function () {
        /*
         SELECT \* FROM dbo.UserName
        */
    }
});

selectAll(null, function(err, result) {
        if (err) { console.log("error "); return;}
        console.log(result);
});

When I execute this query I get the following error : 

Missing method System.Data.SqlClient.SqlCommand::ExecuteReaderAsync(CommandBehavior) in assembly /usr/local/lib/mono/gac/System.Data/4.0.0.0__b77a5c561934e089/System.Data.dll, referenced in assembly /home/merca/login/oauth-server/node_modules/edge-sql/lib/edge-sql.dll

I have run npm test in the edge module and I get 69 tests complete (11 seconds), as far as I can see edge-sql does not have any tests.

I am running on Ubuntu 14.04 with Mono JIT compiler version 3.4.0

**Comment by agracio** [comment]
Project moved to https://github.com/agracio/edge-sql, supports .NET Standard
