### ISSUE TITLE
SqlCommand Properties

### ISSUE THREAD

**Issue by kplatter** [tjanczuk/edge-sql#15]
I would like to be able to set properties of the SqlCommand object, such as CommandTimeout (see https://msdn.microsoft.com/en-us/library/System.Data.SqlClient.SqlCommand(v=vs.110).aspx) I am willing to make the modifications and submit PR but would like some input on how best to pass them in.  One thought is to use a special named parameter like _CommandProperties and do not load it in the AddParameters function but process it after the command is created in the ExecuteQuery function....  Thoughts?

**Comment by agracio** [comment]
CommandTimeout added https://github.com/agracio/edge-sql
