### ISSUE TITLE
Odd connection string behavior

### ISSUE THREAD

**Issue by getglad** [tjanczuk/edge-sql#19]
I am finding that a connection string fails when using a server name with a slash in it.

For instance `Server=servername;Database=dbname;Integrated Security=True` works but `Server=servername\secondpart;Database=dbname;Integrated Security=True` does not work. The response is `error: 40 - Could not open a connection to SQL Server`.

The error response is more or less "The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections".

What is odd is that even if my server is `servername\secondpart`, if I put just `servername` in the connection string, it will connect to `servername\secondpart`.

I'm happy to provide more explanation, but that is all I'm really seeing.

**Comment by Miramac** [comment]
Maybe a missing escape for the backslash? Try: servername\\secondpart

**Comment by getglad** [comment]
Ah - yup - that was it. Thanks for the clarification
