### ISSUE TITLE
Cast to integer fails when a column is declared as smallint in SQL SERVER

### ISSUE THREAD

**Issue by BaumgartnerWilliam** [tjanczuk/edge-sql#20]
Hello there,

When a column is declared as "smallint" in SQL SERVER, we get a "short" back in **C#**. And trying to cast in back to "int" fails since it got encapsulated as an "Object" in EdgeCompiler.cs.

**Ex.:**

```
 short aNumber = 9;
 object o = aNumber;
 int number = (int)aNumber; // -> fails;
```

To adress it, we've to add

```
                    else if (type == typeof(short))
                    {
                        resultRecord[i] = (int)(short)resultRecord[i];
                    }
```

in compiler.cs.

Hope, it helps.

**Comment by agracio** [comment]
Fixed https://github.com/agracio/edge-sql
