### ISSUE TITLE
Stored procedure support

### ISSUE THREAD

**Issue by abmclin** [tjanczuk/edge-sql#8]
When I read the source code, I noticed it has support for executing stored procedures which was added in Nov 2013. I tried it out and it seems to work fine in my test cases.

Before I go ahead and commit to using this functionality, I was wondering if there are additional reasons why this hasn't yet been advertised in edge's documentation.

Appreciate it.

Alex

**Comment by mikeelston** [comment]
@abenjm I know this is old. But do you have any examples of how you called a stored proc with edge?

**Comment by Miramac** [comment]
@mikeelston you can call stored procedure with `EXEC` eg: `EXEC sp_YouAwesomeStoredProc`
````javascript
edge.func('sql', 'EXEC sp_YouAwesomeStoredProc');
````


But due to lack of activity in this project I would recommend another SQL lib. My favorite: https://github.com/tediousjs/tedious
